version: '3.1'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017    
    # restart: always
    # command: --smallfiles
    container_name: app_mongodb
    volumes:
      - ./data/mongodb:/data/db